# Generated by Django 4.0.1 on 2022-02-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('mat', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birthD', models.DateField()),
            ],
        ),
    ]
