# Generated by Django 4.0.1 on 2022-03-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=68, unique=True, verbose_name='email adress')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='nom du patient')),
                ('tel_number', models.CharField(max_length=13, null=True, verbose_name='numéro de tel')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='d')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
